services:
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - docker-network
    restart: always
  
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - docker-network
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    env_file: .env
    volumes:
      - /home/tboussad/data/mariadb_data:/var/lib/mysql
    networks:
      - docker-network
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    volumes:
      - /home/tboussad/data/redis_data:/usr/local/etc/redis/redis.conf
    networks:
      - docker-network
    restart: always

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - /home/tboussad/data/wordpress_data:/var/www/wordpress
    networks:
      - docker-network
    expose:
      - "9000"
      - "80"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - /home/tboussad/data/wordpress_data:/var/www/wordpress
    networks:
      - docker-network
    restart: always

volumes:
  wordpress_data:
  mariadb_data:
  redis_data:
  portainer_data:

networks:
  docker-network:
    driver: bridge
