services:
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always
  
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    env_file: .env
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
      - site
    restart: always
  
  site:
    build: ./requirements/bonus/site
    container_name: site
    image: site
    expose:
      - "80"
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tboussad/data/mariadb_data
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tboussad/data/wordpress_data

networks:
  inception:
    name: inception
    driver: bridge